# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.0010e-38, 1.0102e-38, 8.4490e-39],
        [1.0102e-38, 9.0919e-39, 1.0102e-38],
        [8.9082e-39, 8.4489e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0714, 0.5362, 0.9910],
        [0.8636, 0.2665, 0.1159],
        [0.7067, 0.1337, 0.7123],
        [0.3271, 0.2253, 0.2146],
        [0.7403, 0.8219, 0.3624]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.0714, 0.5362, 0.9910],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.3271, 0.2253, 0.2146],
        [0.7403, 0.8219, 0.3624]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [14]:
h = torch.Tensor(2,17)
j = torch.FloatTensor(3,1)
k = torch.LongTensor(5,2,1)
k[:] = 7
l = torch.ByteTensor(5)
l[:] = 0
l[1:4] = 1

print('h')
print(h)
print('j')
print(j)
print('k')
print(k)
print('l')
print(l)



h
tensor([[9.0919e-39, 1.0102e-38, 8.9082e-39, 8.4489e-39, 9.6428e-39, 8.4490e-39,
         9.6429e-39, 9.2755e-39, 1.0286e-38, 9.0919e-39, 8.9082e-39, 9.2755e-39,
         8.4490e-39, 1.0194e-38, 9.0919e-39, 8.4490e-39, 1.0653e-38],
        [9.9184e-39, 8.4490e-39, 8.9082e-39, 8.9082e-39, 8.7245e-39, 1.0653e-38,
         9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0102e-38, 9.9184e-39, 9.5510e-39,
         1.0102e-38, 9.9184e-39, 1.0102e-38, 4.2246e-39, 1.1112e-38]])
j
tensor([[1.4013e-45],
        [0.0000e+00],
        [0.0000e+00]])
k
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
l
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [15]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.9986, 0.6206, 1.3542],
        [2.0856, 2.0304, 2.0733],
        [2.2325, 2.0251, 2.7370],
        [0.6871, 1.1380, 0.9371],
        [1.2554, 1.4394, 1.1569]])


### 2.2 Addition: syntax 2

In [16]:
print(torch.add(x, y))

tensor([[0.9986, 0.6206, 1.3542],
        [2.0856, 2.0304, 2.0733],
        [2.2325, 2.0251, 2.7370],
        [0.6871, 1.1380, 0.9371],
        [1.2554, 1.4394, 1.1569]])


### 2.3 Addition: giving an output tensor

In [17]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9986, 0.6206, 1.3542],
        [2.0856, 2.0304, 2.0733],
        [2.2325, 2.0251, 2.7370],
        [0.6871, 1.1380, 0.9371],
        [1.2554, 1.4394, 1.1569]])


### 2.4 Addition: in-place

adds `x`to `y`

In [18]:
y.add_(x)
print(y)

tensor([[0.9986, 0.6206, 1.3542],
        [2.0856, 2.0304, 2.0733],
        [2.2325, 2.0251, 2.7370],
        [0.6871, 1.1380, 0.9371],
        [1.2554, 1.4394, 1.1569]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [19]:
print(x[:, 1])

tensor([0.5362, 2.0000, 2.0000, 0.2253, 0.8219])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [27]:
r = torch.ones(5,2)
print(r)
t = torch.Tensor.numpy(r)
print(t)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")